modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="charming_chisels"
version="1.0.0"
displayName="Charming Chisels"
displayURL="https://prcrichards.wixsite.com/portfolio"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Chisels and stuff."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.charming_chisels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration