modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="charming_chisels"
version="1.0.0"
displayName="Charming Chisels"
displayURL="https://prcrichards.wixsite.com/portfolio"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Chisels and stuff."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.charming_chisels]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.charming_chisels]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




[[mixins]]
    config="mixins.charming_chisels.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration